@startuml tic-tac-toe

class Board {
    + board: String[]

    - clearBoard()
}

class Player {
    - p1-name: String
    - p2-name: String
    + currentPlayer: String

    - setPlayerName()
    - getPlayerName()
    + switchPlayer()
}

class Game {
    - gameStatus: String
    - turnStatus: String
    - winnConditions: int[]
    - cpuInfo: String

    - checkGameStatus()
    - switchTurn()
    - execCPUChoice()
}

class Event {
    - messageElement: HtmlElement
    - buttonElement: HtmlElement

    - handleClick()
    - displayPlayerName()
    - displayResult()
}

@enduml