@startuml Architecture-Template

' HTMLファイルをnodeで作成し、"HTML"と名前をつける
node "HTMLファイル" as HTML {
    ' 要素名とclass,IDを格納したコンポーネントを作成し、"E"と名前をつける
    component "要素1\nID: uniqueElement\nクラス: commonClass" as E1
    component "要素2\nクラス: commonClass" as E2
    component "要素3\nクラス: anotherClass" as E3
}

node "CSSファイル" as CSS {
    ' CSSクラス名を格納したコンポーネントを作成し、"C"と名前をつける
    component ".commonClass" as C1
    component "#uniqueElement" as C2
    component ".anotherClass" as C3
}

node "JavaScriptファイル" as JS {
    ' DOM操作メソッドを格納したコンポーネントを作成し、"J"と名前をつける
    component "getElementById('uniqueElement')" as J1
    component "getElementsByClassName('commonClass')" as J2
}

' 矢印で関連を示す
E1 --> C1
E1 --> C2
E2 --> C1
E3 --> C3

J1 --> E1 : "ID取得"
J2 --> E1 : "クラス取得"
J2 --> E2 : "クラス取得"

@enduml